# Import libraries

In [1]:
import pandas as pd
import numpy as np
import datetime
from collections import Counter

# Load the training csv's and combine them into one dataframe

In [2]:
# load all 8 training csv's
df1 = pd.read_csv('reviews/train-1.csv')
df2 = pd.read_csv('reviews/train-2.csv')
df3 = pd.read_csv('reviews/train-3.csv')
df4 = pd.read_csv('reviews/train-4.csv')
df5 = pd.read_csv('reviews/train-5.csv')
df6 = pd.read_csv('reviews/train-6.csv')
df7 = pd.read_csv('reviews/train-7.csv')
df8 = pd.read_csv('reviews/train-8.csv')

# combine the dataframes into one big dataframe
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8])

# Show the head of the data

In [3]:
df.head()

Unnamed: 0  product_id  product_parent                product_title vine  \
0           9  B001N2MZT8       903886718             Green Zone [DVD]    N   
1          11  B00GCBVE0Q       282740618     Le secret de Green Knowe    N   
2          19  1423165691       883799517         A Disney Sketchbook.    N   
3          33  0061091480       623343977         Your Erroneous Zones    N   
4          34  B00HZ4CYOY       647510225  König der Mathematik Junior    N   

  verified_purchase     review_headline  \
0                 Y          green zone   
1                 Y                 NaN   
2                 N        okay mais...   
3                 N            Arrogant   
4                 Y  Tớllé Máthé Ápp...   

                                         review_body review_date  \
0  I found at first it was a little difficult to ...  2010-11-15   
1  J'ai aimé cette histoire. Les acteurs - et sur...  2014-11-23   
2  est-ce une coincidence que la plupart des prin...  2012-12-22   
3  Wáyné Dyér is á pớpúlár áméricán pérsớnál grớw...  2009-07-21   
4  .....unsere Kids mögen diese Art des Lernens. ...  2015-06-01   

   marketplace_id  product_category_id  label  
0               1                    3  False  
1               2                    3  False  
2               0                    0  False  
3               0                    0   True  
4               0                    1  False

# Check if the unnamed column could be the review id

In [4]:
# print the number of rows and number of unique values in the unnamed column
# if they match, we can assume that it's the review_id
print(len(df['Unnamed: 0']), len(df))

9614 9614


# Most frequent values analysis
This could find default or placeholder values

In [5]:
# iterate over the columns and print the most frequent values
for label, content in df.items():
    print(label)
    print(content.mode())
    print()

Unnamed: 0
0           1
1           2
2           3
3           4
4           5
        ...  
9609    11993
9610    11994
9611    11995
9612    11998
9613    11999
Length: 9614, dtype: int64

product_id
0    B00FAPF5U0
dtype: object

product_parent
0    600633062
dtype: int64

product_title
0    Gone Girl
dtype: object

vine
0    N
dtype: object

verified_purchase
0    Y
dtype: object

review_headline
0    Five Stars
dtype: object

review_body
0    Great
dtype: object

review_date
0    2015-01-02
dtype: object

marketplace_id
0    0
dtype: int64

product_category_id
0    3
dtype: int64

label
0    False
dtype: bool



# Unique values analysis
This could find broken values in columns with just a couple of unique values.

In [6]:
# iterate over the columns and get the unique values
for label, content in df.items():
    print(label)
    print(content.unique())
    print()

Unnamed: 0
[    9    11    19 ... 11951 11953 11998]

product_id
['B001N2MZT8' 'B00GCBVE0Q' '1423165691' ... 'B000026FJ6' 'B00K6S2HS4'
 'B00B1COIRC']

product_parent
[903886718 282740618 883799517 ... 475533906  96406179 716679008]

product_title
['Green Zone [DVD]' 'Le secret de Green Knowe' 'A Disney Sketchbook.' ...
 'The Songs of Distant Earth' 'Tolles Album' 'Populaire']

vine
['N' 'Y']

verified_purchase
['Y' 'N']

review_headline
['green zone' nan 'okay mais...' ... 'Native (Gold Edition)'
 'Coup de coeur pour ce film adorable et original' 'Dans la lignée du 1er']

review_body
["I found at first it was a little difficult to associate Matt Damon as anything else but Jason Bourne.But as the film settled in I forgot Jason.The story wasn't overely bright but was conclusive as to what it was all about.That is the Americans covering a story which has already been told.i.e The Big Cover Up,of the Iraq affair.Overall I thought it was a good film , forget the politics watch the film.Good

# Check the rows with NaN values
The unique values analysis showed that the review_headline could be NaN, so we check the whole dataframe on NaN values. It seems that 715 rows don't have a review headline.

In [7]:
# show the rows with null in the 
df[df['review_headline'].isnull()]

Unnamed: 0  product_id  product_parent  \
1             11  B00GCBVE0Q       282740618   
7             49  B00005JYAX       581643936   
35           383  B000024611       769213394   
62           642  B000050FII       676028219   
78           912  B009CAMJWQ       779021042   
...          ...         ...             ...   
1084       11277  B005FGMBY2       558593095   
1122       11631  B00AFBJIVQ       178375143   
1129       11706  B00FAC2GKA       383229535   
1131       11791  B0058HDHAK       766029498   
1140       11889  B00000J2SQ       743214338   

                                          product_title vine  \
1                              Le secret de Green Knowe    N   
7                                               Memento    N   
35                                  Phil Collins...Hits    N   
62                       Fight Club [Édition Collector]    N   
78    Jason Bourne : L'Héritage [Edition Limitée - B...    N   
...                                                 ...  ...   
1084                         Les Frères Grimm [Blu-ray]    N   
1122                                  Les cinq légendes    N   
1129                                Brain Salad Surgery    N   
1131                                  One (Remasterisé)    N   
1140                          Straight Between The Eyes    N   

     verified_purchase review_headline  \
1                    Y             NaN   
7                    N             NaN   
35                   Y             NaN   
62                   N             NaN   
78                   N             NaN   
...                ...             ...   
1084                 Y             NaN   
1122                 Y             NaN   
1129                 Y             NaN   
1131                 Y             NaN   
1140                 N             NaN   

                                            review_body review_date  \
1     J'ai aimé cette histoire. Les acteurs - et sur...  2014-11-23   
7     Le film est excellent niveau suspense,... Je l...  2002-09-28   
35    Un peu trop mou ce ne sont pas les versions le...  2014-08-29   
62    Un film comme l'on en voit désormais très peu,...  2000-12-02   
78    Un peu déçu par cet épisode qui n'est pas à la...  2013-08-14   
...                                                 ...         ...   
1084  Selon les gouts me direz-vous...<br />C'est vr...  2014-12-11   
1122  J'étais plutot retissante d'aller voir ce film...  2013-05-11   
1129  Je suis extrêmement déçu..<br />Cette édition ...  2014-07-25   
1131  C'est une compilation incontournable et qui pe...  2014-02-08   
1140  2éme opus Fm avec Joe Lynn Turner au chant, mê...  2004-12-24   

      marketplace_id  product_category_id  label  
1                  2                    3  False  
7                  0                    3   True  
35                 2                    3  False  
62                 2                    3  False  
78                 2                    3   True  
...              ...                  ...    ...  
1084               2                    3  False  
1122               2                    3   True  
1129               2                    6   True  
1131               2                    6  False  
1140               2                    3   True  

[715 rows x 12 columns]

# Check which columns have NaN values
Other columns could also contain NaN values, so this is checked below. This way we know which columns we might have to fix.

In [8]:
# iterate over the columns and check if any row has NaN for this column
for label, content in df.items():
    print(label)
    print(content.isnull().any())
    print()

Unnamed: 0
False

product_id
False

product_parent
False

product_title
True

vine
False

verified_purchase
False

review_headline
True

review_body
False

review_date
True

marketplace_id
False

product_category_id
False

label
False



# Group the data on the product_id column
We expect the products to have the same product title, product parent and product category_id

In [9]:
# group the data on the product id 
df_gb = df.groupby('product_id')

## Get the products with multiple product titles

In [10]:
# get the counts and number of unique values per product_id group
aggs = df_gb.agg(['nunique']).reset_index(drop=False)

# print all rows with more than one unique product title
multiple_titles = aggs[aggs['product_title','nunique'] > 1]['product_id']

# most common titles of product ids with multiple titles 
titles= [[x, df_gb.get_group(x)['product_title'].mode()] for x in multiple_titles]
titles

[['0007288387',
  0            I Heart New York (I Heart Series)
  1    I Heart New York (I Heart Series, Book 1)
  dtype: object],
 ['0061438294',
  0    What Every BODY is Saying: An Ex-FBI Agent&#82...
  1    What Every BODY is Saying: An Ex-FBI Agent&#82...
  dtype: object],
 ['0099579936',
  0    Fifty Shades of Grey: Book One of the Fifty Sh...
  dtype: object],
 ['0224098101',
  0    Bridget Jones: Mad About the Boy
  1               Bridget est de retour
  dtype: object],
 ['0345529057',
  0    Bien mieux que la série, qui est pourtant géniale
  1    George R. R. Martin's A Game of Thrones 4-Book...
  dtype: object],
 ['0345803485',
  0    Fifty Shades of Grey: Book One of the Fifty Sh...
  1    Fifty Shades of Grey: Book One of the Fifty Sh...
  dtype: object],
 ['0375836675',
  0    I Am the Messenger
  1    I am the Messenger
  dtype: object],
 ['0385484518',
  0    Tuesdays with Morrie: An Old Man, A Young Man ...
  dtype: object],
 ['0590353403',
  0    Harry Potter and th

### Interesting data:
I think that the spacing in front of the titles is a weird print thing.

```
 0                                              Awesome
 1    Harry Potter, volume 1: Harry Potter and the P...
 dtype: object,
 
 0    American IV : The Man Comes Around
 1    American IV:  The Man Comes Around
 dtype: object,
 
 0    Sticks  + Stones
 1     Sticks + Stones
 dtype: object,
 
 0           Obscured By Clouds (remastered)
 1    Obscured By Clouds [Discovery Edition]
 dtype: object,
 
 0    Doctor Who - Complete Series 1-4 Box Set [23 D...
 1            Doctor Who: Series 1 - 4 Collection [DVD]
 dtype: object,
 
 0     Pink - Funhouse Tour/Live in Australia [Blu-ray]
 1    Pink - Funhouse Tour: Live In Australia [Blu-ray]
 dtype: object,
 
 0    Good Evening New York City [2 CD + 1 DVD]
 1      Good evening New York City (2CD + 1DVD)
 dtype: object,
 
 0                     Amazing
 1    Spánnénd bis zúm Schlúss
 2            Zwei von Drei...
 dtype: object,
 
 0     FarmVille 2: Country Escape
 1    FarmVille 2: Raus auf's Land
 dtype: object,
```


In [11]:
# checking the rows of a product
df[df['product_id'] == 'B0024RID60']

Unnamed: 0  product_id  product_parent    product_title vine  \
723        7116  B0024RID60       849107619       Some Girls    N   
458        4659  B0024RID60       849107619  Remarquable !!!    N   

    verified_purchase                     review_headline  \
723                 N  Die letzte große Platte der Stones   
458                 N                          Some Girls   

                                           review_body review_date  \
723  Ich kann mich noch sehr gut an die damaligen P...  2011-10-23   
458  Attention, chef d'oeuvre : Some Girls, sorti e...  2011-02-08   

     marketplace_id  product_category_id  label  
723               0                    6   True  
458               2                    6   True

## Get the products with multiple product titles

In [12]:
# print all rows with more than one unique product parent
multiple_parents = aggs[aggs['product_parent','nunique'] > 1]['product_id']

# most common parents of product ids with multiple parents 
parents = [df_gb.get_group(x)['product_parent'].mode() for x in multiple_parents]
parents

[]

## Get the products with multiple product categories
0 means it's a book, not that it's missing.

In [13]:
# print all rows with more than one unique product category
multiple_categories = aggs[aggs['product_category_id','nunique'] > 1]['product_id']

# print unique category ids of product ids with multiple categories 
categories = [df_gb.get_group(x)['product_category_id'].unique() for x in multiple_categories]
categories

[array([0, 1], dtype=int64),
 array([0, 1], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([1, 0], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([24,  0], dtype=int64),
 array([24,  0], dtype=int64),
 array([0, 1], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([0, 1], dtype=int64),
 array([1, 0], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1], dtype=int64),
 array([ 0, 15], dtype=int64),
 array([0, 1], dtype=int64),
 array([1, 0], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([0, 1], dtype=int64),
 array([ 0, 24], dtype=int64),
 array([ 0, 15], dtype=int64),
 array([0, 1], dtype=int64),
 array([ 0, 15], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 1], dtype=int64),
 array([ 0, 15], dtype=int64),
 array([ 0, 15], dtype=int64),
 array([ 0, 15], dtype=int64),
 array([ 0, 15], dtype=int64),
 array([ 0, 24], dtype=int64),
 array(

# Check the marketplace languages
I saw some review bodies with [escaped characters](https://fantasai.tripod.com/FHQR/Characode/EscCodes.htm), all normal vowels with an accent aigu, random &-signs and html line breaks. The languages of marketplace 1, 2 and 3 are correct. Marketplace 0 contains all 3 languages. We might want to try to predict the language so that we could assign them to a marketplace.

In [14]:
# show the review headline and body of a certain markteplace id 
# 0 = null/no particular marketplace 
# 1 = english 
# 2 = french 
# 3 = german
df[df['marketplace_id'] == 3][['review_headline','review_body']]

review_headline  \
33                                        Ein Klassiker   
117                         alles drin, was man braucht   
153                                               Slash   
304   Star Trek Into Darkness (Blu-ray 3D + DVD + Di...   
384   Minútés tớ Midnight-Dié Kúnst: Linkin Párks sc...   
...                                                 ...   
938                              Placebo Loud like Love   
969                                                Gut!   
1027                außergewöhnlich in Stimmer und Lied   
1066                                 Éinfách núr Súpér.   
1127                                           Fréihéit   

                                            review_body  
33    Ein Muss für jede Plattensammlung. Geht richti...  
117   Für den unschlagbaren Preis von 12,97 Euro ein...  
153   Dá méiné Vớrrédnér dié Détáils béléúchtét hábé...  
304   Spannend wie der erste Star Trek 11. Action ge...  
384   Da in den vergangenen Monaten viele Fake-Alben...  
...                                                 ...  
938   Ich bin total begeistert von dieser CD. Man ka...  
969   Guter Thriller in dem man Tom Cruise sogar den...  
1027  Loreen ist einfach Spitzenklasse. Ich höre sie...  
1066  Bis auf ein oder zwei Stücke, die arg schnulzi...  
1127  Schönés áltés Drámá, wélchés dén únmittélbárén...  

[158 rows x 2 columns]

# Check if there are invalid date values

In [15]:
# funtion that tries to make a datetime from the string
# true means valid, false means invalid, None means NaN
def vali_date(date_text):
    try:
        if not isinstance(date_text, str) and np.isnan(date_text): return None
        datetime.datetime.strptime(date_text, '%Y-%m-%d')
        return True
    except ValueError:
        return False

In [16]:
# get the valid dates (True, False or None) and count them
vali_dates = [vali_date(x) for x in df['review_date']]
Counter(vali_dates)

Counter({True: 9613, None: 1})